version: '3.7'
services:
    webapp:
        build:            
            context: ./ProductsApi
            dockerfile: Dockerfile
        image: flashm01/test1coredb:api 
        ports:
            - "80:80"
            - "433:433"
        depends_on:
            - db
    db:
        build:
            context: ./database
            dockerfile: Dockerfile
            args:
              sapass: abc12x
              dbusr: doc1x            
        image: flashm01/test1coredb:db     
        ports:
            - "5432:5432"